### ISSUE TITLE
404 error during docker run

### ISSUE THREAD

**Issue by rrChauhan** [wireapp/echo-bot#57]
WARN  [2021-03-03 13:32:10,687] org.reflections.Reflections: given scan urls are empty. set urls in the configuration
INFO  [2021-03-03 13:32:11,545] com.wire.bots.logger: Running health checks...
ERROR [2021-03-03 13:32:15,636] com.wire.bots.logger: Outbound failed with: {"code":404,"message":"HTTP 404 Not Found"}. status: 404
java.lang.RuntimeException
        at com.wire.lithium.Server.runHealthChecks(Server.java:270)
        at com.wire.lithium.Server.run(Server.java:152)
        at com.wire.lithium.Server.run(Server.java:73)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at com.wire.bots.echo.Service.main(Service.java:30)

**Comment by dkovacevic** [comment]
Looks like you dont have internet connection from within your container. Can you check that out?
